In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

n = 500

df = pd.DataFrame({
    "Invoice_ID": [f"INV{i:04d}" for i in range(1, n + 1)],
    "Date": pd.to_datetime(
        np.random.choice(
            pd.date_range("2026-01-01", "2026-06-30"),
            n
        )
    ),
    "Branch": np.random.choice(["A", "B", "C"], n),
    "City": np.random.choice(
        ["Lagos", "Abuja", "Ibadan"], n
    ),
    "Gender": np.random.choice(
        ["Male", "Female"], n
    ),
    "Product_Line": np.random.choice(
        [
            "Food and Beverages",
            "Fashion Accessories",
            "Electronic Accessories",
            "Health and Beauty",
            "Home and Lifestyle",
            "Sports and Travel"
        ],
        n
    ),
    "Unit_Price": np.round(
        np.random.uniform(500, 20000, n), 2
    ),
    "Quantity": np.random.randint(1, 11, n),
    "Payment": np.random.choice(
        ["Cash", "Card", "Bank Transfer"], n
    )
})

df["Total_Sales"] = (
    df["Unit_Price"] * df["Quantity"]
).round(2)

df.to_csv("supermarket_sales.csv", index=False)

print("Dataset created successfully!")
print("Number of transactions:", len(df))

df.head(20)

Dataset created successfully!
Number of transactions: 500

,Invoice_ID,Date,Branch,City,Gender,Product_Line,Unit_Price,Quantity,Payment,Total_Sales
0,INV0001,2026-04-13,B,Ibadan,Female,Home and Lifestyle,8849.89,9,Card,79649.01
1,INV0002,2026-06-29,C,Lagos,Male,Home and Lifestyle,14493.16,2,Bank Transfer,28986.32
2,INV0003,2026-04-03,A,Lagos,Male,Fashion Accessories,14002.50,3,Bank Transfer,42007.50
3,INV0004,2026-01-15,A,Abuja,Female,Electronic Accessories,19829.49,5,Bank Transfer,99147.45
4,INV0005,2026-04-17,C,Abuja,Male,Home and Lifestyle,3003.69,3,Bank Transfer,9011.07
5,INV0006,2026-03-13,B,Abuja,Male,Food and Beverages,2530.14,8,Cash,20241.12
6,INV0007,2026-01-21,B,Ibadan,Female,Home and Lifestyle,14624.61,10,Bank Transfer,146246.10
7,INV0008,2026-04-13,A,Lagos,Male,Fashion Accessories,11778.54,8,Card,94228.32
8,INV0009,2026-05-02,C,Lagos,Female,Sports and Travel,5846.13,8,Cash,46769.04
9,INV0010,2026-03-16,B,Ibadan,Female,Fashion Accessories,2048.68,9,Bank Transfer,18438.12
10,INV0011,2026-03-29,C,Lagos,Female,Sports and Travel,2170.34,4,Cash,8681.36
11,INV0012,2026-04-27,C,Abuja,Male,Sports and Travel,17936.72,5,Card,89683.60
12,INV0013,2026-04-10,A,Abuja,Male,Electronic Accessories,4241.41,5,Bank Transfer,21207.05
13,INV0014,2026-04-14,B,Abuja,Male,Home and Lifestyle,6805.75,8,Card,54446.00
14,INV0015,2026-06-01,A,Lagos,Female,Food and Beverages,4919.80,7,Bank Transfer,34438.60
15,INV0016,2026-05-11,B,Abuja,Male,Food and Beverages,7422.43,9,Bank Transfer,66801.87
16,INV0017,2026-05-30,B,Ibadan,Female,Health and Beauty,1853.76,8,Bank Transfer,14830.08
17,INV0018,2026-02-22,B,Ibadan,Female,Sports and Travel,10621.67,2,Bank Transfer,21243.34
18,INV0019,2026-01-02,B,Lagos,Male,Food and Beverages,1818.44,10,Bank Transfer,18184.40
19,INV0020,2026-03-29,B,Ibadan,Female,Electronic Accessories,16106.95,4,Cash,64427.80

In [2]:
df.shape

(500, 10)

In [3]:
df.columns

Index(['Invoice_ID', 'Date', 'Branch', 'City', 'Gender', 'Product_Line',
       'Unit_Price', 'Quantity', 'Payment', 'Total_Sales'],
      dtype='str')

In [4]:
df.head()

,Invoice_ID,Date,Branch,City,Gender,Product_Line,Unit_Price,Quantity,Payment,Total_Sales
0,INV0001,2026-04-13,B,Ibadan,Female,Home and Lifestyle,8849.89,9,Card,79649.01
1,INV0002,2026-06-29,C,Lagos,Male,Home and Lifestyle,14493.16,2,Bank Transfer,28986.32
2,INV0003,2026-04-03,A,Lagos,Male,Fashion Accessories,14002.50,3,Bank Transfer,42007.50
3,INV0004,2026-01-15,A,Abuja,Female,Electronic Accessories,19829.49,5,Bank Transfer,99147.45
4,INV0005,2026-04-17,C,Abuja,Male,Home and Lifestyle,3003.69,3,Bank Transfer,9011.07

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Invoice_ID    500 non-null    str
 1   Date          500 non-null    datetime64[us]
 2   Branch        500 non-null    str
 3   City          500 non-null    str
 4   Gender        500 non-null    str
 5   Product_Line  500 non-null    str
 6   Unit_Price    500 non-null    float64
 7   Quantity      500 non-null    int32
 8   Payment       500 non-null    str
 9   Total_Sales   500 non-null    float64
dtypes: datetime64[us](1), float64(2), int32(1), str(6)
memory usage: 37.2 KB

In [5]:
df.isnull().sum()

Invoice_ID      0
Date            0
Branch          0
City            0
Gender          0
Product_Line    0
Unit_Price      0
Quantity        0
Payment         0
Total_Sales     0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df["Invoice_ID"].duplicated().sum()

np.int64(0)

In [9]:
df[df["Unit_Price"] <= 0]

Empty DataFrame
Columns: [Invoice_ID, Date, Branch, City, Gender, Product_Line, Unit_Price, Quantity, Payment, Total_Sales]
Index: []

In [10]:
(df["Unit_Price"] <= 0).sum()

np.int64(0)

In [11]:
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [Invoice_ID, Date, Branch, City, Gender, Product_Line, Unit_Price, Quantity, Payment, Total_Sales]
Index: []

In [12]:
(df["Quantity"] <= 0).sum()

np.int64(0)

In [13]:
expected_sales = (df["Unit_Price"] * df["Quantity"]).round(2)
(df["Total_Sales"] != expected_sales).sum()

np.int64(0)

In [14]:
total_revenue = df["Total_Sales"].sum()
print("Total Revenue: ", round(total_revenue, 2))

Total Revenue:  27114588.03

In [15]:
total_transactions = df["Invoice_ID"].nunique()
print("Total Transactions:", total_transactions)

Total Transactions: 500

In [16]:
total_items = df["Quantity"].sum()
print("Total Item Sold:", total_items)

Total Item Sold: 2653

In [18]:
average_transaction = df["Total_Sales"].mean()
print("Average Transaction Value: ",
      round(average_transaction, 2))

Average Transaction Value:  54229.18

In [17]:
highest_transaction = df["Total_Sales"].max()
lowest_transaction = df["Total_Sales"].min()
print("Highest Transaction: ", highest_transaction)
print("Lowest Transaction: ", lowest_transaction)

Highest Transaction:  192807.4
Lowest Transaction:  971.74